# Need a Pathway Tools installer in the same folder.
# Need a Blast directory.
Bootstrap: docker
From: ubuntu:18.04

%files
    pathway-tools-27.0-linux-64-tier1-install /opt
    metacyc_27.0.padmet /opt

%environment
    export PATH="$PATH:/programs/pathway-tools:"
    export PATH="${PATH}:/opt/OrthoFinder"
    export LANG="C.UTF-8"

%post
    mkdir -p /programs/pathway-tools;\
    mkdir -p /home/database/BIOCYC/METACYC/27/;\
    mv /opt/metacyc_27.0.padmet /home/database/BIOCYC/METACYC/27/;\
    apt-get update --fix-missing && apt-get install -y wget build-essential automake mcl ncbi-blast+ && rm -rf /var/lib/apt/lists/*
    
apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    make \
    wget \
    csh \
    git \
    libffi-dev \
    libxm4 \
    r-base \
    python3.7-dev \
    python3-pip \
    iputils-ping \
    screen \
    exonerate \
    gnome-terminal ;\
    apt-get clean; \
    apt-get purge ;\
    mkdir -p /external_folder_ptools;\
    chmod u+x /opt/pathway-tools-27.0-linux-64-tier1-install;\
    ./opt/pathway-tools-27.0-linux-64-tier1-install --InstallDir /programs/pathway-tools --PTOOLS_LOCAL_PATH /external_folder_ptools --InstallDesktopShortcuts 0 --mode unattended;\
     mkdir -p /opt;\
     cp -r /external_folder_ptools/ptools-local/ /opt;\
     rm /opt/pathway-tools-27.0-linux-64-tier1-install;\
    # Install FastME
    cd /opt;\
    wget http://www.atgc-montpellier.fr/download/sources/fastme/fastme-2.1.5.tar.gz;\
    tar xzf fastme-2.1.5.tar.gz fastme-2.1.5/binaries/fastme-2.1.5-linux64;\
    cp fastme-2.1.5/binaries/fastme-2.1.5-linux64 /usr/local/bin/fastme;\
    rm fastme-2.1.5.tar.gz;\
    # Install Diamond
    cd /opt;\
    wget https://github.com/bbuchfink/diamond/releases/latest/download/diamond-linux64.tar.gz;\
    tar xzf diamond-linux64.tar.gz;\
    chmod 777 diamond;\
    cp diamond /usr/local/bin/;\
    rm diamond-linux64.tar.gz;\
    cd /opt;\
    wget https://mmseqs.com/latest/mmseqs-linux-avx2.tar.gz;\
    tar xzf mmseqs-linux-avx2.tar.gz;\
    chmod 777 mmseqs/bin/mmseqs;\
    cp mmseqs/bin/mmseqs /usr/local/bin/;\
    rm mmseqs-linux-avx2.tar.gz;\
    /bin/echo "[ncbi]" > ~/.ncbirc;\
    /bin/echo "Data=Data=/external_folder_blast/blast/data" >> ~/.ncbirc;\
    R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/pvclust/pvclust_2.0-0.tar.gz', repos=NULL, type='source', dependencies=TRUE)";\
    R -e "install.packages('ape', dependencies=TRUE)";\
    python3.7 -m pip install --upgrade pip;\
    python3.7 -m pip install --upgrade setuptools;\
    cd /programs;\
    git clone https://github.com/AuReMe/padmet.git;\
    cd padmet;\
    python3.7 -m pip install -e .;\
    cd ../;\
    python3.7 -m pip install scipy;\
    python3.7 -m pip install requests;\
    python3.7 -m pip install aucome;\
    cd /opt;\
    wget https://github.com/davidemms/OrthoFinder/releases/download/2.5.4/OrthoFinder.tar.gz;\
    tar xzf OrthoFinder.tar.gz;\
    rm OrthoFinder.tar.gz;\
    cd OrthoFinder;\
    ln -s /usr/local/bin/diamond;\
    ln -s /usr/local/bin/fastme;\
    ln -s /usr/local/bin/mmseqs;\
    apt-get remove -y wget build-essential automake;\
    chmod -R 777 /opt/*
