# Need a Pathway-tools installer in the same folder.
Bootstrap: docker
From: ubuntu:18.04

%files
    pathway-tools-23.5-linux-64-tier1-install /tmp
    metacyc_23.5.padmet /tmp

%environment
    export PATH="$PATH:/programs/pathway-tools:"
    export PATH="$PATH:/programs/OrthoFinder-2.3.3:"
    export PATH="$PATH:/programs/diamond:"
    export LANG="C.UTF-8"

%post
    apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    make \
    wget \
    csh \
    git \
    ncbi-blast+ \
    mcl \
    libxm4 \
    vim \
    r-base \
    python3-dev \
    python3-distutils \
    iputils-ping \
    screen \
    exonerate \
    gnome-terminal;\
    apt-get clean; \
    apt-get purge;\
    mkdir -p /programs/ /programs/diamond/ /shared/ /home/database/BIOCYC/METACYC/23/;\
    cd /tmp;\
    mv metacyc_23.5.padmet /home/database/BIOCYC/METACYC/23/ ;\
    mkdir -p /external/folder;\
    chmod u+x pathway-tools-23.5-linux-64-tier1-install;\
    ./pathway-tools-23.5-linux-64-tier1-install --InstallDir /programs/pathway-tools --PTOOLS_LOCAL_PATH /external/folder/ --InstallDesktopShortcuts 0 --mode unattended;\
    mkdir -p /opt/;\
    cp -r /external/folder/ptools-local /opt;\
    rm pathway-tools-23.5-linux-64-tier1-install;\
    cd /programs;\
    wget https://github.com/davidemms/OrthoFinder/releases/download/2.3.3/OrthoFinder-2.3.3.tar.gz;\
    tar xzf OrthoFinder-2.3.3.tar.gz;\
    rm OrthoFinder-2.3.3.tar.gz;\
    wget http://www.atgc-montpellier.fr/download/sources/fastme/fastme-2.1.5.tar.gz;\
    tar xzf fastme-2.1.5.tar.gz fastme-2.1.5/binaries/fastme-2.1.5-linux64;\
    mv fastme-2.1.5/binaries/fastme-2.1.5-linux64 /usr/local/bin/fastme;\
    rm -rf fastme-2.1.5*;\
    cd diamond;\
    wget https://github.com/bbuchfink/diamond/releases/download/v0.9.22/diamond-linux64.tar.gz;\
    tar xzf diamond-linux64.tar.gz;\
    curl https://bootstrap.pypa.io/get-pip.py | python3;\
    R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/UpSetR/UpSetR_1.3.3.tar.gz', repos=NULL, type='source', dependencies=TRUE)";\
    R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/pvclust/pvclust_2.0-0.tar.gz', repos=NULL, type='source', dependencies=TRUE)";\
    R -e "install.packages('https://cran.r-project.org/src/contrib/ape_5.3.tar.gz', repos=NULL, type='source', dependencies=TRUE)";\
    curl https://bootstrap.pypa.io/get-pip.py | python3;\
    pip3 install seaborn scipy intervene lxml rpy2;\
    cd /programs;\
    git clone https://github.com/AuReMe/mpwt.git;\
    cd mpwt;\
    git checkout mpwt_0.5.4;\
    python3 setup.py develop;\
    cd ..;\
    git clone https://github.com/AuReMe/padmet.git;\
    cd padmet;\
    git checkout dev;\
    python3 setup.py develop;\
    cd ..;\
    git clone https://github.com/AuReMe/aucome.git;\
    cd aucome;\
    python3 setup.py develop
