# Need a Pathway-tools installer in the same folder.
Bootstrap: docker
From: ubuntu:18.04

%files
    pathway-tools-23.0-linux-64-tier1-install /tmp

%environment
    export PATH="$PATH:/programs/pathway-tools:"
    export PATH="$PATH:/programs/OrthoFinder-2.3.3:"
    export PATH="$PATH:/programs/diamond:"
    export LANG="C.UTF-8"

%post
    apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    make \
    wget \
    csh \
    git \
    ncbi-blast+ \
    mcl \
    libxm4 \
    vim \
    r-base \
    python3-dev \
    python3-distutils \
    iputils-ping \
    screen \
    exonerate \
    gnome-terminal;\
    apt-get clean; \
    apt-get purge; \
    mkdir /programs/ /programs/diamond/ /shared/;\
    cd /tmp;\
    ls;\
    mkdir -p /external/folder;\
    chmod u+x pathway-tools-23.0-linux-64-tier1-install;\
    ./pathway-tools-23.0-linux-64-tier1-install --InstallDir /programs/pathway-tools --PTOOLS_LOCAL_PATH /external/folder/ --InstallDesktopShortcuts 0 --mode unattended;\
    mkdir -p /opt/;\
    cp -r /external/folder/ptools-local /opt;\
    rm pathway-tools-23.0-linux-64-tier1-install;\
    cd /programs;\
    wget https://github.com/davidemms/OrthoFinder/releases/download/2.3.3/OrthoFinder-2.3.3.tar.gz;\
    tar xzf OrthoFinder-2.3.3.tar.gz;\
    rm OrthoFinder-2.3.3.tar.gz;\
    wget http://www.atgc-montpellier.fr/download/sources/fastme/fastme-2.1.5.tar.gz;\
    tar xzf fastme-2.1.5.tar.gz fastme-2.1.5/binaries/fastme-2.1.5-linux64;\
    mv fastme-2.1.5/binaries/fastme-2.1.5-linux64 /usr/local/bin/fastme;\
    rm -rf fastme-2.1.5*;\
    cd diamond;\
    wget https://github.com/bbuchfink/diamond/releases/download/v0.9.22/diamond-linux64.tar.gz;\
    tar xzf diamond-linux64.tar.gz;\
    curl https://bootstrap.pypa.io/get-pip.py | python3;\
    R -e "install.packages('UpSetR',,dependencies=TRUE, repos='http://cran.rstudio.com/' )";\
    R -e "install.packages('pvclust',,dependencies=TRUE, repos='http://cran.rstudio.com/' )";\
    curl https://bootstrap.pypa.io/get-pip.py | python3;\
    cd /programs;\
    git clone https://github.com/AuReMe/padmet-utils.git;\
    pip3 install padmet mpwt eventlet requests seaborn scipy intervene lxml rpy2 tzlocal;\
    git clone https://github.com/AuReMe/aucome.git;\
    cd aucome;\
    python3 setup.py develop
